apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-boot
  name: docker-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-boot
  template:
    metadata:
      labels:
        app: docker-boot
    spec:
      containers:
        - image: docker-boot:latest
          name: docker-boot-e2e
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-boot
  name: docker-boot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: docker-boot
